export { default as Home } from './Home'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as GetRiders } from './riders/GetRiders'
export { default as Contact } from './Contact'
export { default as RequestDemo } from './RequestDemo'
